### ISSUE TITLE
Lightfall with mohist 1.16.5

### ISSUE THREAD

**Issue by Alkasym** [ArclightPowered/lightfall#14]
Hi, i have an issue with mohist 1.16.5, when i want to connect the player on the server, i have an error "this server use mods who need forge installed on the client" but i already use a forge version with the same mod like the server and the lightfall client.

Could you help me?

**Comment by IzzelAliz** [comment]
Here's org for Arclight and I cannot provide any help.

**Comment by Alkasym** [comment]
Nice thanks it's work with arclight !
Now I have a new issues... the /server command to teleport the player to another server doesn't work, it is normal?
