### ISSUE TITLE
Packet Decoding : ftbteams

### ISSUE THREAD

**Issue by X-Niter** [ArclightPowered/lightfall#28]
The Stack Trace of the decoding error can be found [Here!](https://gist.github.com/X-Niter/5be25ede83a2bbaa4c2147a2ed0001e9)

On connection to server, PROXY server resports the above stacktrave for Decoding error for ftbteams:team.

No lightfall version decleration on jar, but it's your latest 1.18.2 support download with lightfall client 1.0.0

**Comment by IzzelAliz** [comment]
You need to enable bungeecord mode in spigot.yml in Arclight

**Comment by X-Niter** [comment]
> You need to enable bungeecord mode in spigot.yml in Arclight

I  did; I'll provide more information as I'm sure it's coming down to a backend server issue.
Proxy config.yml [Here!](https://gist.github.com/X-Niter/cf52b24603aa69c1691d2386437bb81f)
BackEnd spigot.yml [Here!](https://gist.github.com/X-Niter/bbff0292a71581477eb7318947335498)

Addons to the proxy/ aka plugins: None
Backend server modifications: A Mohist Forge 1.16.5 SpongeForge does not work with Lightfall and Mohist has what looks like custom patches to work with lightfall.

No crash reports, just logs which are a bit long, the error I reported is directly from the console and matches directly with the log and debug log.

**Comment by IzzelAliz** [comment]
You are using Mohist which is out of my touch.
