### ISSUE TITLE
Cannot login with create-v0.3.1a

### ISSUE THREAD

**Issue by Mr-Notch** [ArclightPowered/lightfall#5]
while I log in lightfall server it callback me this:
![image](https://user-images.githubusercontent.com/55701169/113974423-7ca6d700-9870-11eb-93c0-f3ac27ca086f.png)

lightfall cmd:
![image](https://user-images.githubusercontent.com/55701169/113974452-8a5c5c80-9870-11eb-8b3f-44d9f66c1bda.png)

arclight (arclight-forge-1.16-1.0.16):
![image](https://user-images.githubusercontent.com/55701169/113974508-9ea05980-9870-11eb-9081-dbf9d2ef5422.png)

mod (client):
the server just install create-v0.3.1a
![image](https://user-images.githubusercontent.com/55701169/113974639-db6c5080-9870-11eb-9221-a05ba4169f60.png)

through i have some tests, create v0.3e hasno this problem.
hope fix it

**Comment by IzzelAliz** [comment]
Please test with latest build.
